DROP DATABASE IF EXISTS TFG;
CREATE DATABASE TFG;
USE TFG;

-- TABLA USUARIO --
CREATE TABLE USUARIO(
	ID_USER BIGINT AUTO_INCREMENT NOT NULL,
    USUARIO VARCHAR(25) UNIQUE NOT NULL,
    CORREO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    IMAGEN VARCHAR(200),
    DESCRIPCION VARCHAR(100) NOT NULL,
    FECHA_CAMBIO_USER DATE NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_USER)
);

-- TABLA LIBRO --
CREATE TABLE LIBRO(
	ID_LIBRO BIGINT AUTO_INCREMENT NOT NULL,
	API_ID VARCHAR(100) UNIQUE NULL,
	ISBN VARCHAR(30) UNIQUE NULL,
	TITULO VARCHAR(300) NOT NULL,
	AUTOR VARCHAR(300) NULL,
	EDITORIAL VARCHAR(250) NULL,
	NUM_PAGINAS INT NULL,
	SINOPSIS TEXT NULL,
	IMAGEN VARCHAR(500) NULL,
	FECHA_PUBLICACION VARCHAR(20) NULL,
	VALORACION DOUBLE NULL,
	CONSTRAINT PRIMARY KEY(ID_LIBRO)
);

-- TABLA SAGA --
CREATE TABLE SAGA(
    ID_SAGA BIGINT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL UNIQUE,
    TIPO ENUM('SAGA', 'TRILOGIA', 'BILOGIA', 'TETRALOGIA', 'COLECCION', 'SERIE') NOT NULL,
    CONSTRAINT PRIMARY KEY(ID_SAGA)
);

-- RELACION LIBRO - SAGA --
CREATE TABLE LIBRO_SAGA(
    ID_LS BIGINT AUTO_INCREMENT NOT NULL,
    LIBRO_ID BIGINT NOT NULL,
    SAGA_ID BIGINT NOT NULL,
    NUMERO_ORDEN INT NULL,
    CONSTRAINT PRIMARY KEY(ID_LS),
    CONSTRAINT UK_LIBRO_SAGA UNIQUE(LIBRO_ID, SAGA_ID),
    FOREIGN KEY(LIBRO_ID) REFERENCES LIBRO(ID_LIBRO) ON DELETE CASCADE,
    FOREIGN KEY(SAGA_ID) REFERENCES SAGA(ID_SAGA) ON DELETE CASCADE
);

-- TABLA USUARIO LIBRO --
CREATE TABLE USER_LIBRO(
    ID_UL BIGINT AUTO_INCREMENT NOT NULL,
	USER_ID BIGINT NOT NULL,
    LIBRO_ID BIGINT NOT NULL,
    ESTADO ENUM ('LEIDO', 'LEYENDO', 'PENDIENTE') NULL,
    CONSTRAINT PRIMARY KEY (ID_UL),
	FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER),
    FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID_LIBRO)
);

-- TABLA OPINION --
CREATE TABLE OPINION(
	ID_OPINION BIGINT AUTO_INCREMENT NOT NULL,
    USER_ID BIGINT NOT NULL,
    LIBRO_ID BIGINT NOT NULL,
    COMENTARIO TEXT NULL,
    VALORACION INT NULL CHECK (VALORACION BETWEEN 1 AND 5),
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PRIMARY KEY (ID_OPINION),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID_LIBRO) ON DELETE CASCADE
    );

-- TABLA FORO --
CREATE TABLE FORO(
	ID_FORO BIGINT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(40) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    IMAGEN VARCHAR(200) NULL,
    CREADOR_ID BIGINT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_FORO),
    FOREIGN KEY (CREADOR_ID) REFERENCES USUARIO(ID_USER)
);

-- TABLA USUARIO FORO --
CREATE TABLE USUARIO_FORO (
    ID_UF BIGINT AUTO_INCREMENT NOT NULL,
	USER_ID BIGINT NOT NULL,
    FORO_ID BIGINT NOT NULL,
    SIGUIENDO BOOLEAN DEFAULT FALSE,
    FAVORITO BOOLEAN DEFAULT FALSE,
    CONSTRAINT PRIMARY KEY (ID_UF),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (FORO_ID) REFERENCES FORO(ID_FORO) ON DELETE CASCADE
);

-- TABLA MENSAJES DEL FORO --
CREATE TABLE MENSAJE_FORO(
	ID_MENSAJE_FORO BIGINT AUTO_INCREMENT NOT NULL,
    USER_ID BIGINT NOT NULL,
    FORO_ID BIGINT NOT NULL,
    CONTENIDO_MSF TEXT NOT NULL,
    FECHA DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_MENSAJE_FORO),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER),
    FOREIGN KEY (FORO_ID) REFERENCES FORO(ID_FORO)
);

-- TABLA MENSAJES PRIVADOS --
CREATE TABLE MENSAJE_PRIVADO(
	ID_MENSAJE_PRIVADO BIGINT AUTO_INCREMENT NOT NULL,
    EMISOR_ID BIGINT NOT NULL,
    RECEPTOR_ID BIGINT NOT NULL,
    CONTENIDO_MSP TEXT NOT NULL,
    FECHA DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_MENSAJE_PRIVADO),
    FOREIGN KEY (EMISOR_ID) REFERENCES USUARIO(ID_USER),
    FOREIGN KEY (RECEPTOR_ID) REFERENCES USUARIO(ID_USER)
);
-- TABAL GENERO --
CREATE TABLE GENERO (
    ID_GENERO BIGINT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_GENERO)
);

CREATE TABLE USUARIO_GENERO (
	ID_UG BIGINT AUTO_INCREMENT,
    USER_ID BIGINT,
    GENERO_ID BIGINT,
    CONSTRAINT PRIMARY KEY (ID_UG),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (GENERO_ID) REFERENCES GENERO(ID_GENERO) ON DELETE CASCADE
);

CREATE TABLE LIBRO_GENERO (
	ID_LG BIGINT AUTO_INCREMENT,
    LIBRO_ID BIGINT,
    GENERO_ID BIGINT,
    UNIQUE (LIBRO_ID, GENERO_ID),
    CONSTRAINT PRIMARY KEY(ID_LG),
	FOREIGN KEY(LIBRO_ID) REFERENCES LIBRO(ID_LIBRO)ON DELETE CASCADE,
	FOREIGN KEY(GENERO_ID) REFERENCES GENERO(ID_GENERO) ON DELETE CASCADE
);

