DROP DATABASE IF EXISTS TFG;
CREATE DATABASE TFG;
USE TFG;

-- TABLA USUARIO --
CREATE TABLE USUARIO(
	ID_USER BIGINT AUTO_INCREMENT NOT NULL,
    USUARIO VARCHAR(25) UNIQUE NOT NULL,
    CORREO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    IMAGEN VARCHAR(200),
    DESCRIPCION VARCHAR(100) NOT NULL,
    FECHA_CAMBIO_USER DATE NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_USER)
);

-- TABLA LIBRO --
CREATE TABLE LIBRO(
	ID_LIBRO BIGINT AUTO_INCREMENT NOT NULL,
	API_ID VARCHAR(100) UNIQUE NULL,
	ISBN VARCHAR(30) UNIQUE NULL,
	TITULO VARCHAR(300) NOT NULL,
	AUTOR VARCHAR(300) NULL,
	EDITORIAL VARCHAR(250) NULL,
	NUM_PAGINAS INT NULL,
	SINOPSIS TEXT NULL,
	IMAGEN VARCHAR(500) NULL,
	FECHA_PUBLICACION VARCHAR(20) NULL,
	VALORACION DOUBLE NULL,
	TIPO VARCHAR(50) NULL,
	CONSTRAINT PRIMARY KEY(ID_LIBRO)
);
-- TABLA USUARIO LIBRO --
CREATE TABLE USER_LIBRO(
    ID_UL BIGINT AUTO_INCREMENT NOT NULL,
	USER_ID BIGINT NOT NULL,
    LIBRO_ID BIGINT NOT NULL,
    ESTADO ENUM ('LEIDO', 'EN_PROCESO', 'PENDIENTE') NULL,
    CONSTRAINT PRIMARY KEY (ID_UL),
	FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER),
    FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID_LIBRO)
);

-- TABLA OPINION --
CREATE TABLE OPINION(
	ID_OPINION BIGINT AUTO_INCREMENT NOT NULL,
    USER_ID BIGINT NOT NULL,
    LIBRO_ID BIGINT NOT NULL,
    COMENTARIO TEXT NULL,
    VALORACION INT NULL CHECK (VALORACION BETWEEN 1 AND 5),
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PRIMARY KEY (ID_OPINION),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (LIBRO_ID) REFERENCES LIBRO(ID_LIBRO) ON DELETE CASCADE
    );

-- TABLA FORO --
CREATE TABLE FORO(
	ID_FORO BIGINT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(40) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    IMAGEN VARCHAR(200) NULL,
    CREADOR_ID BIGINT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_FORO),
    FOREIGN KEY (CREADOR_ID) REFERENCES USUARIO(ID_USER)
);

-- TABLA USUARIO FORO --
CREATE TABLE USUARIO_FORO (
    ID_UF BIGINT AUTO_INCREMENT NOT NULL,
	USER_ID BIGINT NOT NULL,
    FORO_ID BIGINT NOT NULL,
    SIGUIENDO BOOLEAN DEFAULT FALSE,
    FAVORITO BOOLEAN DEFAULT FALSE,
    CONSTRAINT PRIMARY KEY (ID_UF),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (FORO_ID) REFERENCES FORO(ID_FORO) ON DELETE CASCADE
);

-- TABLA MENSAJES DEL FORO --
CREATE TABLE MENSAJE_FORO(
	ID_MENSAJE_FORO BIGINT AUTO_INCREMENT NOT NULL,
    USER_ID BIGINT NOT NULL,
    FORO_ID BIGINT NOT NULL,
    CONTENIDO_MSF TEXT NOT NULL,
    FECHA DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_MENSAJE_FORO),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER),
    FOREIGN KEY (FORO_ID) REFERENCES FORO(ID_FORO)
);

-- TABLA MENSAJES PRIVADOS --
CREATE TABLE MENSAJE_PRIVADO(
	ID_MENSAJE_PRIVADO BIGINT AUTO_INCREMENT NOT NULL,
    EMISOR_ID BIGINT NOT NULL,
    RECEPTOR_ID BIGINT NOT NULL,
    CONTENIDO_MSP TEXT NOT NULL,
    FECHA DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_MENSAJE_PRIVADO),
    FOREIGN KEY (EMISOR_ID) REFERENCES USUARIO(ID_USER),
    FOREIGN KEY (RECEPTOR_ID) REFERENCES USUARIO(ID_USER)
);
-- TABAL GENERO --
CREATE TABLE GENERO (
    ID_GENERO BIGINT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_GENERO)
);

CREATE TABLE USUARIO_GENERO (
	ID_UG BIGINT AUTO_INCREMENT,
    USER_ID BIGINT,
    GENERO_ID BIGINT,
    CONSTRAINT PRIMARY KEY (ID_UG),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (GENERO_ID) REFERENCES GENERO(ID_GENERO) ON DELETE CASCADE
);

CREATE TABLE LIBRO_GENERO (
	ID_LG BIGINT AUTO_INCREMENT,
    LIBRO_ID BIGINT,
    GENERO_ID BIGINT,
    UNIQUE (LIBRO_ID, GENERO_ID),
    CONSTRAINT PRIMARY KEY(ID_LG),
	FOREIGN KEY(LIBRO_ID) REFERENCES LIBRO(ID_LIBRO)ON DELETE CASCADE,
	FOREIGN KEY(GENERO_ID) REFERENCES GENERO(ID_GENERO) ON DELETE CASCADE
);

INSERT INTO GENERO (NOMBRE) VALUES ('Fantasía');
INSERT INTO GENERO (NOMBRE) VALUES ('Fantasía Épica');
INSERT INTO GENERO (NOMBRE) VALUES ('Urban Fantasy');
INSERT INTO GENERO (NOMBRE) VALUES ('Paranormal');

INSERT INTO GENERO (NOMBRE) VALUES ('Romance');
INSERT INTO GENERO (NOMBRE) VALUES ('Dark Romance');
INSERT INTO GENERO (NOMBRE) VALUES ('Romance Histórico');
INSERT INTO GENERO (NOMBRE) VALUES ('Erótico');

INSERT INTO GENERO (NOMBRE) VALUES ('Terror');
INSERT INTO GENERO (NOMBRE) VALUES ('Misterio');
INSERT INTO GENERO (NOMBRE) VALUES ('Thriller');
INSERT INTO GENERO (NOMBRE) VALUES ('Policíaco');
INSERT INTO GENERO (NOMBRE) VALUES ('Novela Negra');
INSERT INTO GENERO (NOMBRE) VALUES ('Psicológico');

INSERT INTO GENERO (NOMBRE) VALUES ('Ciencia Ficción');
INSERT INTO GENERO (NOMBRE) VALUES ('Cyberpunk');
INSERT INTO GENERO (NOMBRE) VALUES ('Distopía');
INSERT INTO GENERO (NOMBRE) VALUES ('Steampunk');

INSERT INTO GENERO (NOMBRE) VALUES ('Aventura');
INSERT INTO GENERO (NOMBRE) VALUES ('Acción');
INSERT INTO GENERO (NOMBRE) VALUES ('Drama');
INSERT INTO GENERO (NOMBRE) VALUES ('Humor');
INSERT INTO GENERO (NOMBRE) VALUES ('Comedia');

INSERT INTO GENERO (NOMBRE) VALUES ('Histórico');
INSERT INTO GENERO (NOMBRE) VALUES ('Novela Histórica');
INSERT INTO GENERO (NOMBRE) VALUES ('Contemporáneo');

INSERT INTO GENERO (NOMBRE) VALUES ('Juvenil');
INSERT INTO GENERO (NOMBRE) VALUES ('Infantil');

INSERT INTO GENERO (NOMBRE) VALUES ('Mitología');
INSERT INTO GENERO (NOMBRE) VALUES ('Realismo Mágico');
INSERT INTO GENERO (NOMBRE) VALUES ('Sobrenatural');
INSERT INTO GENERO (NOMBRE) VALUES ('Vampiros');
INSERT INTO GENERO (NOMBRE) VALUES ('Hombres Lobo');

INSERT INTO GENERO (NOMBRE) VALUES ('LGBTQ+');

INSERT INTO GENERO (NOMBRE) VALUES ('Ficción');
INSERT INTO GENERO (NOMBRE) VALUES ('No Ficción');

INSERT INTO GENERO (NOMBRE) VALUES ('Biografía');
INSERT INTO GENERO (NOMBRE) VALUES ('Poesía');
INSERT INTO GENERO (NOMBRE) VALUES ('Ensayo');
INSERT INTO GENERO (NOMBRE) VALUES ('Filosofía');
INSERT INTO GENERO (NOMBRE) VALUES ('Psicología');
INSERT INTO GENERO (NOMBRE) VALUES ('Autoayuda');
INSERT INTO GENERO (NOMBRE) VALUES ('Desarrollo Personal');

INSERT INTO GENERO (NOMBRE) VALUES ('Negocios');
INSERT INTO GENERO (NOMBRE) VALUES ('Economía');
INSERT INTO GENERO (NOMBRE) VALUES ('Tecnología');
INSERT INTO GENERO (NOMBRE) VALUES ('Programación');
INSERT INTO GENERO (NOMBRE) VALUES ('Educación');

INSERT INTO GENERO (NOMBRE) VALUES ('Arte');
INSERT INTO GENERO (NOMBRE) VALUES ('Música');
INSERT INTO GENERO (NOMBRE) VALUES ('Cocina');
INSERT INTO GENERO (NOMBRE) VALUES ('Viajes');
INSERT INTO GENERO (NOMBRE) VALUES ('Religión');
INSERT INTO GENERO (NOMBRE) VALUES ('Espiritualidad');

INSERT INTO GENERO (NOMBRE) VALUES ('Manga');
INSERT INTO GENERO (NOMBRE) VALUES ('Cómic');
INSERT INTO GENERO (NOMBRE) VALUES ('Novela Gráfica');
INSERT INTO GENERO (NOMBRE) VALUES ('Superhéroes');